### ISSUE TITLE
Finance Big 4 Parity 

### ISSUE THREAD

**Issue by jesusantguerrero** [jesusantguerrero/atmosphere#168]
# Overview

Finance management is one of the main concerns of the app. With a strong financial core this could be self-hosted and accomplish the same things that payed options (Finance Big 4) out there and more:

- Budgeting
- Transactions
- Transaction Labels
- Categories
- Accounts
- Payees
- Watchlists*
- scheduled transactions*
- inter budget transactions*
- transaction templates*

## Tasks:
This is more mobile mode style fixes:

### Budget
  - [x] #171
  - [x] #172
  - [x] #173
  - [x] #174
  - [x] #175
  - [x] #176
  - [x] #177
  - [x] #178
  - [x] #199
  - [ ] #198
  - [ ] Change Budget*

### Accounts
 - [ ] #194

### Transactions
 - [ ] #195
 - [ ] #196
 - [ ] #197
### General
 - [ ] Add backup options (Security Copy to Google Drive, Email, Start from 0, Remove the content)
 - [ ] Transactions 

### Transactions
  - [x] Show account ledger in default transaction screen for mobiles as transaction filter screen
  - [x] improve Add account modal for mobile
  - [x] #179
